### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'to'

### ISSUE THREAD

**Issue by asah** [IvoryCandy/super-resolution#15]
~/super-resolution$ python3 super_resolve.py --model NTIRE2018_x8.pth --input bo-ky-soup.jpg
Namespace(input='bo-ky-soup.jpg', model='NTIRE2018_x8.pth', output='test.jpg')
Traceback (most recent call last):
  File "super_resolve.py", line 34, in <module>
    model = model.to(device)
AttributeError: 'collections.OrderedDict' object has no attribute 'to'

~/super-resolution$ python3 -c "import torch;print(torch.__version__); import torch.backends.cudnn as cudnn;print(cudnn.version())"
1.0.0
7401

**Comment by Mondayyyy** [comment]
> 
> 
> ~/super-resolution$ python3 super_resolve.py --model NTIRE2018_x8.pth --input bo-ky-soup.jpg
> Namespace(input='bo-ky-soup.jpg', model='NTIRE2018_x8.pth', output='test.jpg')
> Traceback (most recent call last):
> File "super_resolve.py", line 34, in
> model = model.to(device)
> AttributeError: 'collections.OrderedDict' object has no attribute 'to'
> 
> ~/super-resolution$ python3 -c "import torch;print(torch.**version**); import torch.backends.cudnn as cudnn;print(cudnn.version())"
> 1.0.0
> 7401

I have the same problem.
Error: AttributeError: 'SRCNNTrainer' object has no attribute 'cuda'
Can you tell me how to resolve it?
Thank you for your help.
